config/routes.rb
SkilZ::Application.routes.draw do
  root :to => redirect('/skilzusers')

  devise_for :skilzusers

  resources :skilzusers

end

app/models/skilzuser.rb
class Skilzuser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :accountType, :coreid
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/skilzusers_controller.rb
class SkilzusersController < ApplicationController
  before_filter :authenticate_skilzuser!
  
  # GET /skilzusers
  # GET /skilzusers.json
  def index
    @skilzusers = Skilzuser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skilzusers }
    end
  end

  # GET /skilzusers/1
  # GET /skilzusers/1.json
  def show
    @skilzuser = Skilzuser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skilzuser }
    end
  end

  # GET /skilzusers/new
  # GET /skilzusers/new.json
  def new
    @skilzuser = Skilzuser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skilzuser }
    end
  end

  # GET /skilzusers/1/edit
  def edit
    @skilzuser = Skilzuser.find(params[:id])
  end

  # POST /skilzusers
  # POST /skilzusers.json
  def create
    @skilzuser = Skilzuser.new(params[:skilzuser])

    respond_to do |format|
      if @skilzuser.save
        format.html { redirect_to @skilzuser, notice: 'Skilzuser was successfully created.' }
        format.json { render json: @skilzuser, status: :created, location: @skilzuser }
      else
        format.html { render action: "new" }
        format.json { render json: @skilzuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skilzusers/1
  # PUT /skilzusers/1.json
  def update
    @skilzuser = Skilzuser.find(params[:id])

    respond_to do |format|
      if @skilzuser.update_attributes(params[:skilzuser])
        format.html { redirect_to @skilzuser, notice: 'Skilzuser was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skilzuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skilzusers/1
  # DELETE /skilzusers/1.json
  def destroy
    @skilzuser = Skilzuser.find(params[:id])
    @skilzuser.destroy

    respond_to do |format|
      format.html { redirect_to skilzusers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skilzusers_helper.rb
module SkilzusersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SkilZ</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/skilzusers/_form.html.erb
<%= form_for(@skilzuser) do |f| %>
  <% if @skilzuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skilzuser.errors.count, "error") %> prohibited this skilzuser from being saved:</h2>

      <ul>
      <% @skilzuser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :coreid %><br />
    <%= f.text_field :coreid %>
  </div>
  <div class="field">
    <%= f.label :accountType %><br />
    <%= f.number_field :accountType %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skilzusers/edit.html.erb
<h1>Editing skilzuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @skilzuser %> |
<%= link_to 'Back', skilzusers_path %>

app/views/skilzusers/index.html.erb
<h1>Listing skilzusers</h1>

<table>
  <tr>
    <th>Coreid</th>
    <th>Accounttype</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @skilzusers.each do |skilzuser| %>
  <tr>
    <td><%= skilzuser.coreid %></td>
    <td><%= skilzuser.accountType %></td>
    <td><%= link_to 'Show', skilzuser %></td>
    <td><%= link_to 'Edit', edit_skilzuser_path(skilzuser) %></td>
    <td><%= link_to 'Destroy', skilzuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Skilzuser', new_skilzuser_path %>

app/views/skilzusers/new.html.erb
<h1>New skilzuser</h1>

<%= render 'form' %>

<%= link_to 'Back', skilzusers_path %>

app/views/skilzusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Coreid:</b>
  <%= @skilzuser.coreid %>
</p>

<p>
  <b>Accounttype:</b>
  <%= @skilzuser.accountType %>
</p>


<%= link_to 'Edit', edit_skilzuser_path(@skilzuser) %> |
<%= link_to 'Back', skilzusers_path %>